apiVersion: v2
name: vault-issuer
description: A cert-manager issuer that signs certificates using HashiCorp Vault.
type: application
version: v0.0.0
appVersion: v0.0.0
home: https://github.com/cert-manager/vault-issuer
sources:
  - https://github.com/cert-manager/vault-issuer
maintainers:
  - name: cert-manager-maintainers
    email: cert-manager-maintainers@googlegroups.com
    url: https://cert-manager.io
keywords:
  - cert-manager
  - vault
  - issuer
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/prerelease: "true"
